version: '3.9'

services:
  nginx:
    build:
      context: nginx
    image: nginx:custom
    container_name: pie01_nginx
    hostname: ghost-nginx
    ports:
      - "${NGINX_PORT:-443}:443"
      - "80:80"
    restart: unless-stopped
    depends_on:
      - ghost
    volumes:
      - nginx-certs:/etc/nginx/certs:ro
      - letsencrypt:/etc/letsencrypt:ro
    networks:
      - main-network

  ghost:
    build:
      context: ghost
    image: ghost:custom
    container_name: pie01_ghost
    hostname: ghost
    restart: always
    depends_on:
      - ghost-db
    environment:
      - NODE_ENV=production
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=root
      - database__connection__password=${DB_PASSWORD}
      - database__connection__database=ghost
      - database__connection__charset=utf8mb4
      - mail__options__host=postfix
      - mail__options__port=25
    #ports:
    #  - "2368:2368"
    volumes:
      - $PWD/ghost/config.production.json:/var/lib/ghost/config.production.json
      - ghost-content:/var/lib/ghost/content:z
    networks:
      - main-network
      - db-network
      - postfix-network

  ghost-db:
    image: mysql:latest
    container_name: pie01_mysql
    hostname: ghost-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=ghost
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ghost-mysql:/var/lib/mysql
    networks:
      - db-network
  
  postfix:
    build:
      context: postfix
    image: postfix:custom
    container_name: pie01_postfix
    hostname: postfix
    restart: always
    networks:
      - postfix-network
      - rsyslog-network
    env_file:
      - .env
    environment:
      - SMTP_USERNAME=$SMTP_USERNAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - TZ=${TIME_ZONE}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${RSYSLOG_SUBNET_PREFIX}.1:${RSYSLOG_PORT}"
        syslog-format: "${RSYSLOG_FORMAT}"
        tag: "{{.Name}}/{{.ID}}"
    ports:
       - "${POSTFIX_PORT}:25"
    cap_add:
      - SYSLOG
  
  syslogd: 
    build:
      context: rsyslog
    image: rsyslog:custom
    container_name: pie01_rsyslog 
    hostname: rsyslog 
    restart: always
    volumes: 
      - rsyslog_home:/var/log
    networks:
      - rsyslog-network
    ports: 
      - "${RSYSLOG_PORT}:514"
      - "${RSYSLOG_PORT}:514/udp"
    cap_add:
      - SYSLOG
    environment:
      - TZ=${TIME_ZONE}

  commento:
    image: registry.gitlab.com/commento/commento:latest
    container_name: pie01_commento
    hostname: commento
    restart: always
    environment:
      # - COMMENTO_SMTP_HOST=smtp.example.com
      # - COMMENTO_SMTP_PORT=587
      # - COMMENTO_SMTP_USERNAME=user@example.com
      # - COMMENTO_SMTP_PASSWORD=password
      # - COMMENTO_SITE_URL=https://example.com
      # - COMMENTO_SITE_NAME=My Commento Site
      # - COMMENTO_POSTGRES_HOST=postgres
      # - COMMENTO_POSTGRES_USER=commento
      # - COMMENTO_POSTGRES_PASSWORD=commento
      # - COMMENTO_POSTGRES_DB=commento
      # - COMMENTO_ALLOW_NESTED=1
      - COMMENTO_ORIGIN=https://comment.pie01.com
      - COMMENTO_PORT=8080
      - COMMENTO_POSTGRES=postgres://postgres:postgres@commento-db:5432/commento?sslmode=disable
    depends_on:
      - commento-db
    networks:
      - main-network
      - db-network
      - postfix-network
    ports:
      - "8080:8080"

  commento-db:
    image: postgres:13
    container_name: pie01_postgres
    restart: always
    environment:
      - POSTGRES_DB=commento
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - commento-postgres:/var/lib/postgresql/data
    networks:
      - db-network

volumes:
  ghost-mysql:
    name: pie01_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/mysql
  commento-postgres:
    name: pie01_commento_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/postgres

  nginx-certs:
    name: pie01_certs
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/certs

  letsencrypt:
    name: pie01_letsencrypt
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/letsencrypt

  ghost-content:
    name: pie01_content
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/content

  rsyslog_home:
    name: rsyslog_home
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/rsyslog

networks:
  main-network:
    name: pie01_web_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${WEB_SUBNET_PREFIX}.0/24
          gateway: ${WEB_SUBNET_PREFIX}.1
  db-network:
    name: pie01_db_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DB_SUBNET_PREFIX}.0/24
          gateway: ${DB_SUBNET_PREFIX}.1
  postfix-network:
    name: pie01_postfix_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${POSTFIX_SUBNET_PREFIX}.0/24
          gateway: ${POSTFIX_SUBNET_PREFIX}.1
  rsyslog-network:
    name: pie01_rsyslog_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${RSYSLOG_SUBNET_PREFIX}.0/24
          gateway: ${RSYSLOG_SUBNET_PREFIX}.1
