version: '3.9'

services:
  nginx:
    build:
      context: nginx
    image: nginx:custom
    container_name: pie01_nginx
    hostname: ghost-nginx
    ports:
      - "${NGINX_PORT:-443}:443"
      - "80:80"
    restart: unless-stopped
    depends_on:
      - ghost
    volumes:
      - nginx-certs:/etc/nginx/certs:ro
      - letsencrypt:/etc/letsencrypt:ro
    networks:
      - main-network

  ghost:
    build:
      context: ghost
    image: ghost:custom
    container_name: pie01_ghost
    hostname: ghost
    restart: always
    depends_on:
      - ghost-db
    environment:
      - NODE_ENV=production
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=root
      - database__connection__password=${DB_PASSWORD}
      - database__connection__database=ghost
      - database__connection__charset=utf8mb4
      - mail__options__host=postfix
      - mail__options__secure=true
      - mail__options__port=${POSTFIX_INNER_PORT}
    #ports:
    #  - "2368:2368"
    volumes:
      - $PWD/ghost/config.production.json:/var/lib/ghost/config.production.json
      - ghost-content:/var/lib/ghost/content:z
    networks:
      - main-network
      - db-network
      - postfix-network

  ghost-db:
    image: mysql:latest
    container_name: pie01_mysql
    hostname: ghost-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=ghost
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ghost-mysql:/var/lib/mysql
    networks:
      - db-network
    
  # mail:
  #   image: bytemark/smtp
  #   restart: always

  plausible-db:
    image: postgres:14-alpine
    container_name: pie01_plausible_db
    hostname: plausible-db
    restart: always
    volumes:
      - plausible-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$PLAUSIBLE_DB_PASSWORD
    networks:
      - main-network

  plausible-event-db:
    image: clickhouse/clickhouse-server:22.6-alpine
    container_name: pie01_plausible_event_db
    hostname: plausible-event-db
    restart: always
    volumes:
      - plausible-event-data:/var/lib/clickhouse
      - $PWD/plausible/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - $PWD/plausible/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - main-network

  plausible:
    image: plausible/analytics:latest
    container_name: pie01_plausible
    hostname: plausible
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible-db
      - plausible-event-db
      # - mail
    ports:
      - 8000:8000
    environment:
      - BASE_URL=$PLAUSIBLE_BASE_URL
      - DATABASE_URL=postgres://postgres:${PLAUSIBLE_DB_PASSWORD}@plausible-db:5432/plausible
      - CLICKHOUSE_DATABASE_URL=http://plausible-event-db:8123/plausible_events
      - SECRET_KEY_BASE=$PLAUSIBLE_SECRET
      - ADMIN_USER_EMAIL=$PLAUSIBLE_ADMIN_EMAIL
      - ADMIN_USER_NAME=$PLAUSIBLE_ADMIN_USER
      - ADMIN_USER_PWD=$PLAUSIBLE_ADMIN_PWD
      - CLICKHOUSE_DATABASE_USER=$CLICKHOUSE_DB_USER
      - CLICKHOUSE_DATABASE_PASSWORD=$CLICKHOUSE_DB_PASSWORD
    networks:
      - main-network
  
  postfix:
    build:
      context: postfix
    image: postfix:custom
    container_name: pie01_postfix
    hostname: postfix
    restart: always
    networks:
      - postfix-network
      - rsyslog-network
    env_file:
      - .env
    environment:
      - SMTP_USERNAME=$SMTP_USERNAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - TZ=${TIME_ZONE}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${RSYSLOG_SUBNET_PREFIX}.1:${RSYSLOG_PORT}"
        syslog-format: "${RSYSLOG_FORMAT}"
        tag: "{{.Name}}/{{.ID}}"
    ports:
       - "${POSTFIX_PORT}:${POSTFIX_INNER_PORT}"
    cap_add:
      - SYSLOG
  
  syslogd: 
    build:
      context: rsyslog
    image: rsyslog:custom
    container_name: pie01_rsyslog 
    hostname: rsyslog 
    restart: always
    volumes: 
      - rsyslog-home:/var/log
    networks:
      - rsyslog-network
    ports: 
      - "${RSYSLOG_PORT}:514"
      - "${RSYSLOG_PORT}:514/udp"
    cap_add:
      - SYSLOG
    environment:
      - TZ=${TIME_ZONE}

  remark:
    image: umputun/remark42:latest
    container_name: pie01_remark42
    hostname: remark42
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - "8080:8080"

    environment:
      - REMARK_URL=$REMARK_URL
      - SITE=$REMARK_SITE
      - SECRET=$REMARK_SECRET
      - STORE_BOLT_PATH=/srv/var/db
      - BACKUP_PATH=/srv/var/backup
      - DEBUG=true
      - AUTH_ANON=true
      - AUTH_GOOGLE_CID=$REMARK_GOOGLE_CID
      - AUTH_GOOGLE_CSEC=$REMARK_GOOGLE_CSEC
      - AUTH_GITHUB_CID=$REMARK_GITHUB_CID
      - AUTH_GITHUB_CSEC=$REMARK_GITHUB_CSEC
      - AUTH_FACEBOOK_CID=$REMARK_FACEBOOK_CID
      - AUTH_FACEBOOK_CSEC=$REMARK_FACEBOOK_CSEC
      - AUTH_TELEGRAM=true
      - TELEGRAM_TOKEN=$REMARK_TELEGRAM_TOKEN
      - TELEGRAM_TIMEOUT=5s
      - NOTIFY_TELEGRAM_CHAN=
      - AUTH_EMAIL_ENABLE=true
      - AUTH_EMAIL_FROM=$REMARK_EMAIL_FROM
      - AUTH_EMAIL_SUBJ=$REMARK_AUTH_SUBJ
      - AUTH_EMAIL_CONTENT_TYPE=text/html
      - ADMIN_SHARED_EMAIL=$REMARK_EMAIL_FROM
      - NOTIFY_USERS=email
      - NOTIFY_EMAIL_FROM=$REMARK_EMAIL_FROM
      - NOTIFY_EMAIL_VERIFICATION_SUBJ=Email verification
      - NOTIFY_ADMINS=email
      - NOTIFY_QUEUE=100
      - ADMIN_SHARED_ID=$REMARK_ADMIN
      - SMTP_HOST=postfix
      - SMTP_PORT=${POSTFIX_INNER_PORT}
      # - AUTH_SAME_SITE=none
      # DON'T set SMTP username/password
      # - SMTP_USERNAME=$SMTP_USERNAME
      # - SMTP_PASSWORD=$SMTP_PASSWORD
      # - SMTP_TLS=true
      - SMTP_TIMEOUT=20s
      # Enable it only for the initial comment import or for manual backups
      # - ADMIN_PASSWD=<your secret password>
    volumes:
      - remark42:/srv/var
    networks:
      - main-network
      - postfix-network

volumes:
  ghost-mysql:
    name: pie01_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/mysql

  nginx-certs:
    name: pie01_certs
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/certs

  letsencrypt:
    name: pie01_letsencrypt
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/letsencrypt

  ghost-content:
    name: pie01_content
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/content

  rsyslog-home:
    name: pie01_rsyslog
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/rsyslog

  remark42:
    name: pie01_remark42
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/remark42
  
  plausible-data:
    name: pie01_plausible_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/plausible/postgres
  
  plausible-event-data:
    name: pie01_plausible_event_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/plausible/clickhouse

networks:
  main-network:
    name: pie01_web_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${WEB_SUBNET_PREFIX}.0/24
          gateway: ${WEB_SUBNET_PREFIX}.1
  db-network:
    name: pie01_db_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DB_SUBNET_PREFIX}.0/24
          gateway: ${DB_SUBNET_PREFIX}.1
  postfix-network:
    name: pie01_postfix_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${POSTFIX_SUBNET_PREFIX}.0/24
          gateway: ${POSTFIX_SUBNET_PREFIX}.1
  rsyslog-network:
    name: pie01_rsyslog_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${RSYSLOG_SUBNET_PREFIX}.0/24
          gateway: ${RSYSLOG_SUBNET_PREFIX}.1
